apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubernetes.fullname" . }}
  labels:
    {{- include "kubernetes.labels" . | nindent 4 }}
data:
  config: |-
    http_address = "0.0.0.0:{{ .Values.oauthConfig.port }}"
    redirect_url = {{ .Values.oauthConfig.redirectUrl | quote }}
    provider= "oidc"
    oidc_issuer_url= {{ .Values.oauthConfig.oidcIssuerUrl | quote }}
    client_id = {{ .Values.oauthConfig.clientId | quote }}
    client_secret = {{ .Values.oauthConfig.clientSecret | quote }}
    cookie_name= {{ .Values.oauthConfig.cookieName | quote }}
    cookie_secret = {{ .Values.oauthConfig.cookieSecret | quote }}
    email_domains = {{ .Values.oauthConfig.emailDomains | quote }}
    upstreams = [{{ .Values.oauthConfig.upstreams | quote }}]
    custom_sign_in_logo = "-"

  default.conf: |-
    server {
      listen {{ .Values.portal.port }};
      root /usr/share/nginx/html;
      index index.html;
    }

  index.html: |-
    <!doctype html>

    <html lang="en">
    <head>
      <meta charset="utf-8">
      <title> Qovery Portal </title>
    </head>

    <body>
      <div>
        <h2>I'm in !</h2>
      </div>
    </body>
    </html>
